server:
  port: ${SERVER_PORT:7071}

spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://configserver:1010}
  application:
    name: card
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}   # default to 'test' if not set
  datasource:
    url: ${DB_URL:jdbc:postgresql://host.docker.internal:5432/postgres}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
