server:
  port: ${SERVER_PORT:8076}

spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://configserver:1010}
  application:
    name: eurekaserver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
