eureka:
  instance:
    hostname: eurekaserver  # Important: this must match the container name or service name in Docker
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
