services:
  configserver:
    image: configserver
    container_name: configserver
    ports:
      - "1010:1010"
    environment:
      - SPRING_PROFILES_ACTIVE=native
    networks:
      - microservice-network
    deploy:
      resources:
        limits:
          memory: 700m


  eurekaserver:
    image: eurekaserver
    container_name: eurekaserver
    ports:
      - "8076:8076"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - configserver
    networks:
      - microservice-network
    deploy:
      resources:
        limits:
          memory: 700m

  gatewayserver:
    image: gatewayserver
    container_name: gatewayserver
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - configserver
      - eurekaserver
    networks:
      - microservice-network
    deploy:
      resources:
        limits:
          memory: 700m

  loan:
    image: loan
    container_name: loan
    ports:
      - "9091:9091"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - configserver
      - eurekaserver
    networks:
      - microservice-network
    deploy:
      resources:
        limits:
          memory: 700m



  account:
    image: account
    container_name: account
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - configserver
      - eurekaserver
    networks:
      - microservice-network
    deploy:
      resources:
        limits:
          memory: 700m

  card:
    image: card
    container_name: card
    ports:
      - "7071:7071"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - configserver
      - eurekaserver
    networks:
      - microservice-network
    deploy:
      resources:
        limits:
          memory: 700m

networks:
  microservice-network:
    driver: bridge
